# Generated by Django 4.2 on 2023-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Username')),
                ('followers', models.IntegerField(verbose_name='Followers')),
                ('followings', models.IntegerField(verbose_name='Following')),
            ],
        ),
    ]
