# Generated by Django 4.2 on 2023-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekvizit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Login')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='stats',
            name='followers',
            field=models.CharField(max_length=255, verbose_name='Followers'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='followings',
            field=models.CharField(max_length=255, verbose_name='Following'),
        ),
    ]
